---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .IDENTITY_SERVICE_API_NAME }}
spec:
  egress:
    - {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
      ports:
        - port: 8443
          protocol: TCP
  podSelector:
    matchLabels:
      name: {{ .IDENTITY_SERVICE_API_NAME }}
  policyTypes:
    - Ingress
    - Egress
