spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.url}/auth/realms/${auth.realm}

server:
  servlet.context-path: /api/identity
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
  ssl:
    enabled: ${ssl.enabled:false}
    key-alias: cert
    key-store: /etc/keystore/keystore.p12
    key-store-password: changeit
    key-password: changeit
    key-store-type: PKCS12
    trust-store: ${javax.net.ssl.trustStore:/etc/keystore/cacerts}
    trust-store-password: ${javax.net.ssl.trustStorePassword:changeit}
    trust-store-type: ${javax.net.ssl.trustStoreType:PKCS12}

aws:
  region: ${AWS_REGION:eu-west-2}
  bucket-name: ${aws.s3.identity.scanData:}
  credentials:
    access-key: ${AWS_ACCESS_KEY:}
    secret-Key: ${AWS_SECRET_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus, metrics,loggers"
